# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ex00_pb2 as ex00__pb2


class Ex00Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShips = channel.unary_stream(
                '/ex00.Ex00/GetShips',
                request_serializer=ex00__pb2.Coordinate.SerializeToString,
                response_deserializer=ex00__pb2.Spaceship.FromString,
                )


class Ex00Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetShips(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Ex00Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShips': grpc.unary_stream_rpc_method_handler(
                    servicer.GetShips,
                    request_deserializer=ex00__pb2.Coordinate.FromString,
                    response_serializer=ex00__pb2.Spaceship.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ex00.Ex00', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Ex00(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetShips(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/ex00.Ex00/GetShips',
            ex00__pb2.Coordinate.SerializeToString,
            ex00__pb2.Spaceship.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
