/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "3d_viewer_test.check" instead.
 */
// #include <check.h>
#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#line 1 "3d_viewer_test.check"
#include "3d_viewer.h"

//! === PARSE_VERTEXES ===
START_TEST(parser_main_vertexes) {
#line 7

  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");

  ck_assert_float_eq_tol(a.matrix_vertexes[0], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[1], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[2], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[3], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[4], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[5], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[6], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[7], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[8], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[9], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[10], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[11], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[12], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[13], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[14], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[15], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[16], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[17], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[18], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[19], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[20], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[21], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[22], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[23], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[24], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[25], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[26], 1, 1e-6);
  free_mem(&a);

  //! === PARSE_POLYGONS ===
}
END_TEST

START_TEST(parser_main_polygons) {
#line 45

  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");
  ck_assert_uint_eq(a.matrix_polygons[0], 1);
  ck_assert_uint_eq(a.matrix_polygons[1], 7);
  ck_assert_uint_eq(a.matrix_polygons[2], 7);
  ck_assert_uint_eq(a.matrix_polygons[3], 5);
  ck_assert_uint_eq(a.matrix_polygons[4], 5);
  ck_assert_uint_eq(a.matrix_polygons[5], 1);
  ck_assert_uint_eq(a.matrix_polygons[6], 1);
  ck_assert_uint_eq(a.matrix_polygons[7], 3);
  ck_assert_uint_eq(a.matrix_polygons[8], 3);
  ck_assert_uint_eq(a.matrix_polygons[9], 7);
  ck_assert_uint_eq(a.matrix_polygons[10], 7);
  ck_assert_uint_eq(a.matrix_polygons[11], 1);
  ck_assert_uint_eq(a.matrix_polygons[12], 1);
  ck_assert_uint_eq(a.matrix_polygons[13], 4);
  ck_assert_uint_eq(a.matrix_polygons[14], 4);
  ck_assert_uint_eq(a.matrix_polygons[15], 3);
  ck_assert_uint_eq(a.matrix_polygons[16], 3);
  ck_assert_uint_eq(a.matrix_polygons[17], 1);
  ck_assert_uint_eq(a.matrix_polygons[18], 1);
  ck_assert_uint_eq(a.matrix_polygons[19], 2);
  ck_assert_uint_eq(a.matrix_polygons[20], 2);
  ck_assert_uint_eq(a.matrix_polygons[21], 4);
  ck_assert_uint_eq(a.matrix_polygons[22], 4);
  ck_assert_uint_eq(a.matrix_polygons[23], 1);
  ck_assert_uint_eq(a.matrix_polygons[24], 3);
  ck_assert_uint_eq(a.matrix_polygons[25], 8);
  ck_assert_uint_eq(a.matrix_polygons[26], 8);
  ck_assert_uint_eq(a.matrix_polygons[27], 7);
  ck_assert_uint_eq(a.matrix_polygons[28], 7);
  ck_assert_uint_eq(a.matrix_polygons[29], 3);

  ck_assert_float_eq(a.matrix_polygons[30], 3);
  ck_assert_float_eq(a.matrix_polygons[31], 4);
  ck_assert_float_eq(a.matrix_polygons[32], 4);
  ck_assert_float_eq(a.matrix_polygons[33], 8);
  ck_assert_float_eq(a.matrix_polygons[34], 8);
  ck_assert_float_eq(a.matrix_polygons[35], 3);
  ck_assert_float_eq(a.matrix_polygons[36], 5);
  ck_assert_float_eq(a.matrix_polygons[37], 7);
  ck_assert_float_eq(a.matrix_polygons[38], 7);
  ck_assert_float_eq(a.matrix_polygons[39], 8);
  ck_assert_float_eq(a.matrix_polygons[40], 8);
  ck_assert_float_eq(a.matrix_polygons[41], 5);
  ck_assert_float_eq(a.matrix_polygons[42], 5);
  ck_assert_float_eq(a.matrix_polygons[43], 8);
  ck_assert_float_eq(a.matrix_polygons[44], 8);
  ck_assert_float_eq(a.matrix_polygons[45], 6);
  ck_assert_float_eq(a.matrix_polygons[46], 6);
  ck_assert_float_eq(a.matrix_polygons[47], 5);
  ck_assert_float_eq(a.matrix_polygons[48], 1);
  ck_assert_float_eq(a.matrix_polygons[49], 5);
  ck_assert_float_eq(a.matrix_polygons[50], 5);
  ck_assert_float_eq(a.matrix_polygons[51], 6);
  ck_assert_float_eq(a.matrix_polygons[52], 6);
  ck_assert_float_eq(a.matrix_polygons[53], 1);
  ck_assert_float_eq(a.matrix_polygons[54], 1);
  ck_assert_float_eq(a.matrix_polygons[55], 6);
  ck_assert_float_eq(a.matrix_polygons[56], 6);
  ck_assert_float_eq(a.matrix_polygons[57], 2);
  ck_assert_float_eq(a.matrix_polygons[58], 2);
  ck_assert_float_eq(a.matrix_polygons[59], 1);
  ck_assert_float_eq(a.matrix_polygons[60], 2);
  ck_assert_float_eq(a.matrix_polygons[61], 6);
  ck_assert_float_eq(a.matrix_polygons[62], 6);
  ck_assert_float_eq(a.matrix_polygons[63], 8);
  ck_assert_float_eq(a.matrix_polygons[64], 8);
  ck_assert_float_eq(a.matrix_polygons[65], 2);
  ck_assert_float_eq(a.matrix_polygons[66], 2);
  ck_assert_float_eq(a.matrix_polygons[67], 8);
  ck_assert_float_eq(a.matrix_polygons[68], 8);
  ck_assert_float_eq(a.matrix_polygons[69], 4);
  ck_assert_float_eq(a.matrix_polygons[70], 4);
  ck_assert_float_eq(a.matrix_polygons[71], 2);
  // ck_assert_float_eq_tol(a.matrix_vertexes[72], 0, 1e-6);

  free_mem(&a);

  // ! === PARSE_COUNTS ===
}
END_TEST

START_TEST(parser_main_counts) {
#line 85
  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");
  ck_assert_uint_eq(a.summ_of_vertexes, 27);
  ck_assert_uint_eq(a.summ_of_polygons, 72);
  ck_assert_float_eq_tol(max_coord(&a, 0), 1, 1e-6);
  free_mem(&a);

  // ! === PARSE_SCALE ===
}
END_TEST

START_TEST(parser_main_scale) {
#line 98

  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");
  matrix_scale(&a, 3);

  ck_assert_float_eq_tol(a.matrix_vertexes[0], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[1], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[2], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[3], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[4], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[5], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[6], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[7], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[8], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[9], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[10], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[11], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[12], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[13], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[14], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[15], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[16], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[17], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[18], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[19], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[20], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[21], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[22], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[23], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[24], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[25], 3, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[26], 3, 1e-6);
  free_mem(&a);

  //! === PARSE_ROTATE_X ===
}
END_TEST

START_TEST(parser_main_rotate_x) {
#line 142

  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");

  matrix_rotate(&a, 'x', 2);

  ck_assert_float_eq_tol(a.matrix_vertexes[0], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[1], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[2], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[3], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[4], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[5], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[6], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[7], -0.909297, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[8], -0.416147, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[9], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[10], -0.416147, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[11], 0.909297, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[12], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[13], -1.32544, 1e-5);
  ck_assert_float_eq_tol(a.matrix_vertexes[14], 0.493151, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[15], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[16], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[17], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[18], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[19], -0.909297, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[20], -0.416147, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[21], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[22], -0.416147, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[23], 0.909297, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[24], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[25], -1.32544, 1e-5);
  ck_assert_float_eq_tol(a.matrix_vertexes[26], 0.493151, 1e-6);

  free_mem(&a);

  //! === PARSE_ROTATE_Y ===
}
END_TEST

START_TEST(parser_main_rotate_y) {
#line 181

  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");

  matrix_rotate(&a, 'y', 1);

  ck_assert_float_eq_tol(a.matrix_vertexes[0], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[1], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[2], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[3], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[4], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[5], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[6], -0.841471, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[7], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[8], 0.540302, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[9], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[10], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[11], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[12], -0.841471, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[13], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[14], 0.540302, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[15], 0.540302, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[16], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[17], 0.841471, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[18], -0.301169, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[19], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[20], 1.38177, 1e-5);
  ck_assert_float_eq_tol(a.matrix_vertexes[21], 0.540302, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[22], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[23], 0.841471, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[24], -0.301169, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[25], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[26], 1.38177, 1e-5);
  free_mem(&a);

  // //! === PARSE_ROTATE_Z ===
}
END_TEST

START_TEST(parser_main_rotate_Z) {
#line 220

  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");

  matrix_rotate(&a, 'z', -2.5);

  ck_assert_float_eq_tol(a.matrix_vertexes[0], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[1], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[2], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[3], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[4], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[5], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[6], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[7], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[8], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[9], 0.598472, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[10], -0.801144, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[11], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[12], 0.598472, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[13], -0.801144, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[14], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[15], -0.801144, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[16], -0.598472, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[17], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[18], -0.801144, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[19], -0.598472, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[20], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[21], -0.202671, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[22], -1.39962, 1e-5);
  ck_assert_float_eq_tol(a.matrix_vertexes[23], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[24], -0.202671, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[25], -1.39962, 1e-5);
  ck_assert_float_eq_tol(a.matrix_vertexes[26], 1, 1e-6);
  free_mem(&a);

  //! === PARSE_MOVE_X ===
}
END_TEST

START_TEST(parser_main_move_x) {
#line 260

  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");
  matrix_move(&a, 'x', 8);

  ck_assert_float_eq_tol(a.matrix_vertexes[0], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[1], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[2], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[3], 8, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[4], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[5], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[6], 8, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[7], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[8], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[9], 8, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[10], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[11], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[12], 8, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[13], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[14], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[15], 9, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[16], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[17], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[18], 9, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[19], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[20], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[21], 9, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[22], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[23], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[24], 9, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[25], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[26], 1, 1e-6);
  free_mem(&a);

  //! === PARSE_MOVE_Y ===
}
END_TEST

START_TEST(parser_main_move_y) {
#line 299

  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");
  matrix_move(&a, 'y', 4);

  ck_assert_float_eq_tol(a.matrix_vertexes[0], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[1], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[2], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[3], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[4], 4, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[5], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[6], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[7], 4, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[8], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[9], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[10], 5, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[11], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[12], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[13], 5, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[14], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[15], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[16], 4, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[17], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[18], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[19], 4, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[20], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[21], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[22], 5, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[23], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[24], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[25], 5, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[26], 1, 1e-6);
  free_mem(&a);

  //! === PARSE_MOVE_Z ===
}
END_TEST

START_TEST(parser_main_move_z) {
#line 341

  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");
  matrix_move(&a, 'z', 0);

  ck_assert_float_eq_tol(a.matrix_vertexes[0], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[1], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[2], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[3], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[4], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[5], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[6], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[7], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[8], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[9], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[10], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[11], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[12], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[13], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[14], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[15], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[16], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[17], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[18], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[19], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[20], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[21], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[22], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[23], 0, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[24], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[25], 1, 1e-6);
  ck_assert_float_eq_tol(a.matrix_vertexes[26], 1, 1e-6);
  free_mem(&a);

  // ! === MIN_C ===
}
END_TEST

START_TEST(parser_min_c) {
#line 85
  obj_data a;
  start_parse_obj_file(&a, "cube_test.obj");
  ck_assert_uint_eq(a.summ_of_vertexes, 27);
  ck_assert_uint_eq(a.summ_of_polygons, 72);
  ck_assert_float_eq_tol(min_coord(&a, 0), 0, 1e-6);
  free_mem(&a);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, parser_main_vertexes);
  tcase_add_test(tc1_1, parser_main_scale);

  tcase_add_test(tc1_1, parser_main_polygons);

  tcase_add_test(tc1_1, parser_main_counts);
  tcase_add_test(tc1_1, parser_main_rotate_x);
  tcase_add_test(tc1_1, parser_main_rotate_y);
  tcase_add_test(tc1_1, parser_main_rotate_Z);
  tcase_add_test(tc1_1, parser_main_move_x);
  tcase_add_test(tc1_1, parser_main_move_y);
  tcase_add_test(tc1_1, parser_main_move_z);
  tcase_add_test(tc1_1, parser_min_c);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
