#!/bin/sh.

HEAD_FLAG="-n"
HEAD_FLAG_VAL='1'

TAIL_FLAG="-n"
TAIL_FLAG_VAL="+2"

SORT_FLAG_ONE="-t"
SORT_FLAG_TWO="-k"

SORT_FLAG_ONE_VAL=','
SORT_FLAG_TWO_VAL='2'
SORT_FLAG_THREE_VAL='1'

CSV_FILE="hh.csv"
CSV_FILE_PATH="../ex01/"

RES_FILE="hh_sorted.csv"

head $HEAD_FLAG $HEAD_FLAG_VAL $CSV_FILE_PATH$CSV_FILE > $RES_FILE

tail $TAIL_FLAG $TAIL_FLAG_VAL $CSV_FILE_PATH$CSV_FILE |
sort $SORT_FLAG_ONE $SORT_FLAG_ONE_VAL $SORT_FLAG_TWO $SORT_FLAG_TWO_VAL $SORT_FLAG_TWO $SORT_FLAG_THREE_VAL >> $RES_FILE &&
clear
